### ISSUE TITLE
Script stopped working with the latest YouTube theme update

### ISSUE THREAD

**Issue by Lenmaer67** [skoshy/YouTubeHideChatByDefaultUserscript#2]
YouTube updated their theme and now with the script enabled the chat stays opened, and all the dialogue in there is invisible.

**Comment by swapnilsm** [comment]
Hi @Lenmaer67, 
Adding "button" to the `buttonSelectors` worked for me.

**Comment by Lenmaer67** [comment]
Hello @swapnilsm 
Thanks a lot. That fixed it.

**Comment by skoshy** [comment]
Thanks for bringing this up! I implemented the fix from @swapnilsm in 0.6.0
